# Generated by Django 4.1.5 on 2023-01-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='codigo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='code',
            field=models.CharField(default=None, max_length=10, unique=True, verbose_name='Code'),
            preserve_default=False,
        ),
    ]
