# Generated by Django 4.1.5 on 2023-01-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Code'),
        ),
    ]
